apiVersion: v1
kind: ConfigMap
metadata:
  name: converter-configmap
data:
  MP3_QUEUE: 'mp3'
  VIDEO_QUEUE: 'video'
  MONGODB_URI: 'mongodb://prince:prince1234@mongodb/mp3s?authSource=admin' #nodeip:nodeport
